### PR TITLE
Add CI/CD configuration (Travis-CI, Tox, Coverage, badges)

### LINKED ISSUE #39: Add CI/CD configuration (e.g. Travis-CI, Tox, Coverage, flake8, PyLint)
This project should test releases, changes, pull requests against a continuous integration service in order to make it easier to add new features or apply specific changes, including refactoring.

The project should be tested against all supported (major) versions of Django and Python to make it more transparent and appealing to developers independent from their respective target environment.

Badges in the README would be a nice plus.

### PR DESCRIPTION
**Pull request by bittner**
This PR adds

* configuration for Travis-CI (continuous integration service)
* configuration for Tox (testing against different Python/Django targets)
* configuration for Coverage.py (source code to consider for coverage check)
* nice-looking badges for the README

The configuration is mostly inspired/copied from [django-analytical](https://github.com/jcassee/django-analytical).

Fixes #39. -- I'll do `flake8` and `PyLint` in a separate PR, will be easier to read this way.

### CODE REVIEW

**Comment by samluescher** [comment]
Cool! Please remove the .komodoproject from .gitignore though, that seems overly specific and should probably go into your global .gitignore.

**Comment by bittner** [comment]
Hmm, what's that? `.komodoproject`? Not from me, I just refactored the path. Probably introduced by someone work with the [Komodo IDE](http://komodoide.com/), maybe?

I'll remove it.

**Comment by bittner** [comment]
You'll have to create personal accounts (with your GitHub username) at [Travis-CI](https://travis-ci.org/samluescher/django-media-tree) and [Coveralls.io](https://coveralls.io/r/samluescher/django-media-tree) to make the badges work.

**Comment by bittner** [comment]
Would you mind releasing a new version on PyPI as soon as this is merged and working?

**Comment by bittner** [comment]
Do you mind merging this PR? Anything left to do on my side?

**Comment by bittner** [comment]
@samluescher Don't forget to create accounts on [Travis-CI](https://travis-ci.org/samluescher/django-media-tree), [Coveralls.io](https://coveralls.io/r/samluescher/django-media-tree) and [Landscape.io](https://landscape.io/github/samluescher/django-media-tree/) to make the badges in the README work!

**Pull request merged**
